services:
  api:
    container_name: nde-api
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DB_DRIVER: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: "8080"

  db:
    container_name: nde-db
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
