# fly.toml app configuration file generated for backend-ancient-glitter-1627 on 2025-04-15T20:50:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-ancient-glitter-1627'
primary_region = 'gru'

[build]
  [build.args]
    GO_VERSION = '1.24.1'

[env]
  PORT = ':8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
